export const ADD_EXERCISE = 'ADD_EXERCISE';
export const DELETE_EXERCISE = 'DELETE_EXERCISE';
export const EDIT_EXERCISE = 'EDIT_EXERCISE';
export const FILTER_EXERCISE_UP = 'FILTER_EXERCISE_UP';
export const FILTER_EXERCISE_DOWN = 'FILTER_EXERCISE_DOWN';
export const ADD_DATE_NEW_EXERCISE = 'ADD_DATE_NEW_EXERCISE';